# -*- coding: utf-8 -*-
"""steram5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13H87XIZnLHbhBLmyoVmwwtxMYz8g-arF
"""

from dataclasses import dataclass
import copy
import random

import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset


import pandas as pd

@dataclass
class ExperimentResult:
    dataset: str
    model: str
    seed: int
    task_type: str
    metric_name: str
    metric_value: float
    predictions: np.ndarray
    targets: np.ndarray
    config: dict

class TALENTMLP(nn.Module):
    def __init__(
        self,
        d_in: int,
        d_out: int,
        d_layers: list[int],
        dropout: float,
    ):
        super().__init__()

        self.dropout = dropout
        self.d_out = d_out

        self.layers = nn.ModuleList([
            nn.Linear(
                d_layers[i - 1] if i else d_in,
                d
            )
            for i, d in enumerate(d_layers)
        ])

        self.head = nn.Linear(
            d_layers[-1] if d_layers else d_in,
            d_out
        )

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
            x = F.relu(x)

            if self.dropout:
                x = F.dropout(
                    x,
                    p=self.dropout,
                    training=self.training
                )

        x = self.head(x)

        if self.d_out == 1:
            x = x.squeeze(-1)

        return x

class TorchMLP:
    def __init__(
        self,
        task_type,
        d_layers,
        dropout,
        lr,
        weight_decay,
        seed,
        batch_size=1024,
        max_epoch=200,
        patience=20,
        device=None,
    ):
        self.task_type = task_type
        self.d_layers = d_layers
        self.dropout = dropout

        self.lr = lr
        self.weight_decay = weight_decay

        self.seed = seed
        self.batch_size = batch_size
        self.max_epoch = max_epoch
        self.patience = patience

        if device is None:
            self.device = torch.device(
                "cuda" if torch.cuda.is_available() else "cpu"
            )
        else:
            self.device = torch.device(device)

        self.model = None
        self.classes_ = None

    def _set_seed(self):
        random.seed(self.seed)
        np.random.seed(self.seed)
        torch.manual_seed(self.seed)

        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(self.seed)

    @staticmethod
    def _prepare_X(X):
        # На случай scipy sparse matrix
        if hasattr(X, "toarray"):
            X = X.toarray()

        return np.asarray(X, dtype=np.float32)

    def fit(self, X_train, y_train, X_val, y_val):
        self._set_seed()

        X_train = self._prepare_X(X_train)
        X_val = self._prepare_X(X_val)

        y_train = np.asarray(y_train)
        y_val = np.asarray(y_val)

        is_classification = self.task_type in (
            "binary",
            "multiclass",
        )

        # -------------------------
        # TARGETS
        # -------------------------

        if is_classification:
            self.classes_ = np.unique(y_train)

            class_to_idx = {
                cls: i
                for i, cls in enumerate(self.classes_)
            }

            y_train_encoded = np.array(
                [class_to_idx[y] for y in y_train],
                dtype=np.int64,
            )

            y_val_encoded = np.array(
                [class_to_idx[y] for y in y_val],
                dtype=np.int64,
            )

            d_out = len(self.classes_)

        else:
            y_train_encoded = y_train.astype(np.float32)
            y_val_encoded = y_val.astype(np.float32)

            d_out = 1

        # -------------------------
        # NEURAL NETWORK
        # -------------------------

        d_in = X_train.shape[1]

        self.model = TALENTMLP(
            d_in=d_in,
            d_out=d_out,
            d_layers=self.d_layers,
            dropout=self.dropout,
        ).to(self.device)

        # -------------------------
        # OPTIMIZER
        # -------------------------

        optimizer = torch.optim.AdamW(
            self.model.parameters(),
            lr=self.lr,
            weight_decay=self.weight_decay,
        )

        if is_classification:
            criterion = nn.CrossEntropyLoss()
        else:
            criterion = nn.MSELoss()

        # -------------------------
        # TRAIN DATALOADER
        # -------------------------

        X_train_tensor = torch.tensor(
            X_train,
            dtype=torch.float32,
        )

        if is_classification:
            y_train_tensor = torch.tensor(
                y_train_encoded,
                dtype=torch.long,
            )
        else:
            y_train_tensor = torch.tensor(
                y_train_encoded,
                dtype=torch.float32,
            )

        train_dataset = TensorDataset(
            X_train_tensor,
            y_train_tensor,
        )

        train_loader = DataLoader(
            train_dataset,
            batch_size=self.batch_size,
            shuffle=True,
        )

        # validation tensors

        X_val_tensor = torch.tensor(
            X_val,
            dtype=torch.float32,
            device=self.device,
        )

        if is_classification:
            y_val_tensor = torch.tensor(
                y_val_encoded,
                dtype=torch.long,
                device=self.device,
            )
        else:
            y_val_tensor = torch.tensor(
                y_val_encoded,
                dtype=torch.float32,
                device=self.device,
            )

        # -------------------------
        # EARLY STOPPING
        # -------------------------

        if is_classification:
            best_score = -np.inf
        else:
            best_score = np.inf

        best_state = None
        bad_epochs = 0

        for epoch in range(self.max_epoch):
            # TRAIN

            self.model.train()

            for X_batch, y_batch in train_loader:
                X_batch = X_batch.to(self.device)
                y_batch = y_batch.to(self.device)

                optimizer.zero_grad()

                output = self.model(X_batch)

                loss = criterion(output, y_batch)

                loss.backward()
                optimizer.step()

            # VALIDATION

            self.model.eval()

            with torch.no_grad():
                val_output = self.model(X_val_tensor)

                if is_classification:
                    val_pred = val_output.argmax(dim=1)

                    score = (
                        (val_pred == y_val_tensor)
                        .float()
                        .mean()
                        .item()
                    )

                    improved = score > best_score

                else:
                    rmse = torch.sqrt(
                        torch.mean(
                            (val_output - y_val_tensor) ** 2
                        )
                    ).item()

                    score = rmse

                    improved = score < best_score

            if improved:
                best_score = score
                bad_epochs = 0

                best_state = copy.deepcopy(
                    self.model.state_dict()
                )

            else:
                bad_epochs += 1

            if bad_epochs >= self.patience:
                break

        # Возвращаем лучший checkpoint,
        # а не веса последней эпохи
        if best_state is not None:
            self.model.load_state_dict(best_state)

        return self

    def predict(self, X):
        X = self._prepare_X(X)

        X_tensor = torch.tensor(
            X,
            dtype=torch.float32,
            device=self.device,
        )

        self.model.eval()

        with torch.no_grad():
            output = self.model(X_tensor)

        if self.task_type in ("binary", "multiclass"):
            class_indices = (
                output
                .argmax(dim=1)
                .cpu()
                .numpy()
            )

            return self.classes_[class_indices]

        return output.cpu().numpy()

def prepare_data(model_name, dataset, preprocessor=None):
    if model_name == "catboost":
        frames = [dataset.X_train.copy(), dataset.X_val.copy(), dataset.X_test.copy()]
        for frame in frames:
            for column in dataset.categorical_columns:
                frame[column] = frame[column].fillna("__missing__").astype(str)
        return (
            *frames,
            dataset.y_train,
            dataset.y_val,
            dataset.y_test,
        )

    preprocessor.fit(dataset.X_train)

    def matrix(X, y):
        processed = preprocessor.transform(X, y)
        return torch.cat(
            [part for part in (processed.x_num, processed.x_cat) if part is not None],
            dim=1,
        ).cpu().numpy()

    X_train = matrix(dataset.X_train, dataset.y_train)
    X_val = matrix(dataset.X_val, dataset.y_val)
    X_test = matrix(dataset.X_test, dataset.y_test)

    return X_train, X_val, X_test, dataset.y_train, dataset.y_val, dataset.y_test

def build_model(model_name, task_type, config, seed):

    config = config.copy()
    is_classification = task_type in ("binary", "multiclass")

    if model_name == "catboost":
        from catboost import CatBoostClassifier, CatBoostRegressor

        if config.get("task_type") == "GPU" and torch.cuda.is_available():
            torch.cuda.empty_cache()
        config.setdefault("early_stopping_rounds", 50)
        config.setdefault("eval_metric", "Accuracy" if is_classification else "RMSE")
        config.setdefault("use_best_model", True)
        config.setdefault("allow_writing_files", False)
        if is_classification:
            return CatBoostClassifier(
                **config,
                random_seed=seed
            )
        else:
            return CatBoostRegressor(
                **config,
                random_seed=seed
            )

    elif model_name == "mlp":
            return TorchMLP(
                task_type=task_type,
                seed = seed,
                **config)

    elif model_name == "xgboost":
        from xgboost import XGBClassifier, XGBRegressor

        config.setdefault("early_stopping_rounds", 50)
        config.setdefault("eval_metric", {"binary": "error", "multiclass": "merror", "regression": "rmse"}[task_type])
        if is_classification:
            return XGBClassifier(
                **config,
                random_state=seed
            )
        else:
            return XGBRegressor(
                **config,
                random_state=seed
            )

    else:
        raise ValueError(f"Unknown model: {model_name}")

def fit_model(model, model_name, X_train, X_val, y_train, y_val):
    model_name = model_name.lower()

    if model_name == "catboost":
        model.fit(X_train, y_train, eval_set=(X_val, y_val), verbose=False)

    elif model_name == "xgboost":
        model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=False)

    elif model_name == "mlp":
        model.fit(X_train, y_train, X_val, y_val)

    else:
        raise ValueError(f"Unknown model {model_name}")

    return model

def compute_metric(task_type, y_true, y_pred):
  y_true = np.asarray(y_true).reshape(-1)
  y_pred = np.asarray(y_pred).reshape(-1)
  if y_true.shape != y_pred.shape:
    raise ValueError("Targets and predictions must have matching shapes")

  if task_type in ("binary", "multiclass"):
    return "accuracy", (y_true == y_pred).mean()
  elif task_type == "regression":
    return "rmse", np.sqrt(np.mean((y_true - y_pred) ** 2))
  else:
    raise ValueError(f"Unknown kind of task type: {task_type}")

def suggest_params(trial, model_name):
    model_name = model_name.lower()

    def optional_float(
        name,
        low,
        high,
        log=False,
    ):
        use = trial.suggest_categorical(
            f"use_{name}",
            [False, True],
        )

        if not use:
            return 0.0

        return trial.suggest_float(
            name,
            low,
            high,
            log=log,
        )

    if model_name == "mlp":
        n_layers = trial.suggest_int(
            "n_layers",
            1,
            8,
        )

        d_first = trial.suggest_int(
            "d_first",
            64,
            512,
        )

        if n_layers == 1:
            d_layers = [d_first]

        elif n_layers == 2:
            d_last = trial.suggest_int(
                "d_last",
                64,
                512,
            )

            d_layers = [
                d_first,
                d_last,
            ]

        else:
            d_middle = trial.suggest_int(
                "d_middle",
                64,
                512,
            )

            d_last = trial.suggest_int(
                "d_last",
                64,
                512,
            )

            d_layers = (
                [d_first]
                + [d_middle] * (n_layers - 2)
                + [d_last]
            )

        return {
            "d_layers": d_layers,

            "dropout": optional_float(
                "dropout",
                0.0,
                0.5,
            ),

            "lr": trial.suggest_float(
                "lr",
                1e-5,
                1e-2,
                log=True,
            ),

            "weight_decay": optional_float(
                "weight_decay",
                1e-6,
                1e-3,
                log=True,
            ),

            "batch_size": 1024,
            "max_epoch": 200,
            "patience": 20,
        }

    elif model_name == "catboost":
        return {
            "bagging_temperature": trial.suggest_float(
                "bagging_temperature",
                0.0,
                1.0,
            ),

            "depth": trial.suggest_int(
                "depth",
                3,
                10,
            ),

            "l2_leaf_reg": trial.suggest_float(
                "l2_leaf_reg",
                1.0,
                10.0,
                log=True,
            ),

            "leaf_estimation_iterations": trial.suggest_int(
                "leaf_estimation_iterations",
                1,
                10,
            ),

            "learning_rate": trial.suggest_float(
                "learning_rate",
                1e-5,
                1.0,
                log=True,
            ),

            "iterations": 2000,
        }

    elif model_name == "xgboost":
        return {
            "reg_alpha": optional_float(
                "reg_alpha",
                1e-8,
                100.0,
                log=True,
            ),

            "colsample_bylevel": trial.suggest_float(
                "colsample_bylevel",
                0.5,
                1.0,
            ),

            "colsample_bytree": trial.suggest_float(
                "colsample_bytree",
                0.5,
                1.0,
            ),

            "gamma": optional_float(
                "gamma",
                1e-8,
                100.0,
                log=True,
            ),

            "reg_lambda": optional_float(
                "reg_lambda",
                1e-8,
                100.0,
                log=True,
            ),

            "learning_rate": trial.suggest_float(
                "learning_rate",
                1e-5,
                1.0,
                log=True,
            ),

            "max_depth": trial.suggest_int(
                "max_depth",
                3,
                10,
            ),

            "min_child_weight": trial.suggest_float(
                "min_child_weight",
                1e-8,
                1e5,
                log=True,
            ),

            "subsample": trial.suggest_float(
                "subsample",
                0.5,
                1.0,
            ),

            "n_estimators": 2000,
        }

    else:
        raise ValueError(
            f"Unknown model: {model_name}"
        )

def objective(trial, model_name, dataset, seed, preprocessor, model_config=None):
  config = suggest_params(trial, model_name)
  config.update(model_config or {})
  trial.set_user_attr("config", config)

  X_train, X_val, _, y_train, y_val, _ = prepare_data(model_name, dataset, preprocessor)
  model = build_model(model_name, dataset.task_type, config, seed)
  if model_name == "catboost":
    model.set_params(cat_features=dataset.categorical_columns)
  model = fit_model(model, model_name, X_train, X_val, y_train, y_val)

  y_pred = model.predict(X_val)
  _, metric_value = compute_metric(dataset.task_type, y_val, y_pred)

  return metric_value

def optuna_patience_reached(study, patience=10):
  import optuna

  if patience < 1:
    raise ValueError("Optuna patience must be positive")
  best_value = None
  bad_trials = 0
  for trial in study.get_trials(deepcopy=False, states=(optuna.trial.TrialState.COMPLETE,)):
    improved = best_value is None or (trial.value < best_value if study.direction.name == "MINIMIZE" else trial.value > best_value)
    if improved:
      best_value = trial.value
      bad_trials = 0
    else:
      bad_trials += 1
  return bad_trials >= patience


def stop_optuna_if_no_improvement(study, trial, patience=10):
  if trial.state.name == "COMPLETE" and optuna_patience_reached(study, patience):
    print("Optuna", study.study_name, "stopped: no improvement for", patience, "trials")
    study.stop()


def tune_hyperparameters(model_name, dataset, seed, preprocessor, n_trials, model_config=None, storage=None, study_name=None, optuna_patience=10):
  import optuna

  if dataset.task_type == "regression":
    direction ='minimize'
  else:
    direction ='maximize'

  study = optuna.create_study(
    direction=direction,
    sampler=optuna.samplers.TPESampler(seed=seed),
    storage=storage,
    study_name=study_name,
    load_if_exists=True,
  )
  completed = len(study.get_trials(deepcopy=False, states=(optuna.trial.TrialState.COMPLETE,)))
  remaining = max(0, n_trials - completed)
  print("Optuna", study.study_name, "completed", completed, "remaining", remaining)
  if remaining and not optuna_patience_reached(study, optuna_patience):
    study.optimize(
      lambda trial: objective(trial, model_name, dataset, seed, preprocessor, model_config),
      n_trials=remaining,
      callbacks=[lambda study, trial: stop_optuna_if_no_improvement(study, trial, optuna_patience)],
    )
  elif remaining:
    print("Optuna", study.study_name, "already stopped: no improvement for", optuna_patience, "trials")

  return {**study.best_trial.user_attrs["config"], **(model_config or {})}

def run_experiment(model_name, dataset, seed, config, preprocessor):
  model_name = model_name.lower()
  X_train, X_val, X_test, y_train, y_val, y_test = prepare_data(model_name, dataset, preprocessor)

  model = build_model(model_name, dataset.task_type, config, seed)
  if model_name == "catboost":
    model.set_params(cat_features=dataset.categorical_columns)
  model = fit_model(model, model_name, X_train, X_val, y_train, y_val)

  y_pred = model.predict(X_test)

  metric_name, metric_value = compute_metric(dataset.task_type, y_test, y_pred)

  return ExperimentResult(dataset.dataset_name, model_name, seed, dataset.task_type, metric_name, metric_value, y_pred, y_test, config)

"""## EVAL"""

def run_experiments(model_names, datasets, seeds, preprocessor, n_trials=100, tune_seed=0, model_configs=None):
    results = []

    for dataset in datasets:
        for model_name in model_names:
            model_config = (model_configs or {}).get(model_name, {})
            best_params = tune_hyperparameters(
                model_name=model_name,
                dataset=dataset,
                seed=tune_seed,
                preprocessor=preprocessor,
                n_trials=n_trials,
                model_config=model_config,
            )

            for seed in seeds:
                result = run_experiment(
                    model_name=model_name,
                    dataset=dataset,
                    seed=seed,
                    config=best_params,
                    preprocessor=preprocessor
                )
                results.append(result)

    df = pd.DataFrame([
        {
            "dataset": result.dataset,
            "model": result.model,
            "seed": result.seed,
            "task_type": result.task_type,
            "metric": result.metric_name,
            "metric_value": result.metric_value,
            "config": result.config
        }
        for result in results
    ])

    return df
